// Initial Seed Data: Accessories with Clean, Authentic Product Images
const INITIAL_ACCESSORIES = [
  {
    "id": "acc-01",
    "name": "Spigen EZ Fit Tempered Glass (iPhone 16)",
    "category": "Tempered Glass",
    "brand": "Spigen",
    "sku": "SPG-TG-IP16",
    "price": 1299,
    "offerPrice": 999,
    "stock": 18,
    "warranty": "Lifetime Alignment Warranty",
    "rating": 4.9,
    "reviewsCount": 88,
    "featured": true,
    "image": "https://images.unsplash.com/photo-1596558450255-7c0b7be9d56a?auto=format&fit=crop&w=500&q=80",
    "description": "Auto-alignment tray included. 9H hardness tempered glass with oleophobic coating."
  },
  {
    "id": "acc-02",
    "name": "Edge-to-Edge UV Curved Glass (S25 Ultra)",
    "category": "Tempered Glass",
    "brand": "Websirg Care",
    "sku": "WC-UV-S25U",
    "price": 999,
    "offerPrice": 699,
    "stock": 15,
    "warranty": "1 Month Bubble-Free Warranty",
    "rating": 4.7,
    "reviewsCount": 45,
    "featured": false,
    "image": "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?auto=format&fit=crop&w=500&q=80",
    "description": "Full screen liquid glue UV tempered glass with ultrasonic fingerprint unlock support."
  },
  {
    "id": "acc-03",
    "name": "Ringke Fusion Matte Case (iPhone 16 Pro)",
    "category": "Mobile Covers",
    "brand": "Ringke",
    "sku": "RNK-CS-IP16P",
    "price": 1499,
    "offerPrice": 1299,
    "stock": 12,
    "warranty": "6 Months Anti-Yellowing Guarantee",
    "rating": 4.8,
    "reviewsCount": 60,
    "featured": true,
    "image": "https://images.unsplash.com/photo-1603313011101-320f26a4f6f6?auto=format&fit=crop&w=500&q=80",
    "description": "Mil-grade drop protection with translucent anti-fingerprint frosted back."
  },
  {
    "id": "acc-04",
    "name": "Spigen Liquid Air Shockproof Case (OnePlus 13)",
    "category": "Mobile Covers",
    "brand": "Spigen",
    "sku": "SPG-CS-OP13",
    "price": 1399,
    "offerPrice": 1199,
    "stock": 10,
    "warranty": "6 Months Warranty",
    "rating": 4.8,
    "reviewsCount": 32,
    "featured": false,
    "image": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=500&q=80",
    "description": "Geometric pattern with air cushion technology in slim, lightweight profile."
  },
  {
    "id": "acc-05",
    "name": "MagSafe Liquid Silicone Case (Universal)",
    "category": "Mobile Covers",
    "brand": "Websirg Care",
    "sku": "WC-MAG-SIL",
    "price": 999,
    "offerPrice": 799,
    "stock": 25,
    "warranty": "3 Months Replacement",
    "rating": 4.6,
    "reviewsCount": 76,
    "featured": false,
    "image": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=500&q=80",
    "description": "Silky soft-touch silicone with built-in N52 strong neodymium magnets."
  },
  {
    "id": "acc-06",
    "name": "Apple 20W USB-C Power Adapter",
    "category": "Chargers",
    "brand": "Apple",
    "sku": "APL-CHG-20W",
    "price": 2099,
    "offerPrice": 1900,
    "stock": 14,
    "warranty": "1 Year Apple Official Warranty",
    "rating": 4.9,
    "reviewsCount": 150,
    "featured": true,
    "image": "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=500&q=80",
    "description": "Fast charging adapter compatible with iPhone, iPad, and Apple Watch."
  },
  {
    "id": "acc-07",
    "name": "Samsung 45W Super Fast Power Adapter",
    "category": "Chargers",
    "brand": "Samsung",
    "sku": "SAM-CHG-45W",
    "price": 2999,
    "offerPrice": 2499,
    "stock": 8,
    "warranty": "6 Months Samsung Warranty",
    "rating": 4.8,
    "reviewsCount": 92,
    "featured": false,
    "image": "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&w=500&q=80",
    "description": "Power Delivery 3.0 PPS super fast charger for Galaxy flagships."
  },
  {
    "id": "acc-08",
    "name": "boAt Rockerz 255 Pro+ Bluetooth Neckband",
    "category": "Earphones",
    "brand": "boAt",
    "sku": "BOAT-RCK-255",
    "price": 1999,
    "offerPrice": 1299,
    "stock": 30,
    "warranty": "1 Year boAt Warranty",
    "rating": 4.7,
    "reviewsCount": 240,
    "featured": true,
    "image": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?auto=format&fit=crop&w=500&q=80",
    "description": "40H playback, ASAP charge (10 mins = 10 hours), IPX7 water resistance."
  },
  {
    "id": "acc-09",
    "name": "OnePlus Bullets Wireless Z2 Bluetooth",
    "category": "Earphones",
    "brand": "OnePlus",
    "sku": "OP-BWZ2-BLK",
    "price": 2299,
    "offerPrice": 1999,
    "stock": 22,
    "warranty": "1 Year OnePlus Warranty",
    "rating": 4.8,
    "reviewsCount": 185,
    "featured": true,
    "image": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=500&q=80",
    "description": "12.4mm bass drivers, 30-hour battery life, fast pairing."
  },
  {
    "id": "acc-10",
    "name": "Realme Buds T300 TWS Earbuds",
    "category": "Earphones",
    "brand": "Realme",
    "sku": "RME-T300-WHT",
    "price": 2999,
    "offerPrice": 2199,
    "stock": 16,
    "warranty": "1 Year Brand Warranty",
    "rating": 4.6,
    "reviewsCount": 94,
    "featured": false,
    "image": "https://images.unsplash.com/photo-1608156639585-34a0a56ee6c9?auto=format&fit=crop&w=500&q=80",
    "description": "30dB Active Noise Cancellation, 360 Spatial Audio Effect, 40 hours playback."
  },
  {
    "id": "acc-11",
    "name": "Braided 65W Type-C to Type-C Cable 1.5M",
    "category": "Cables",
    "brand": "Websirg Care",
    "sku": "WC-CBL-65W",
    "price": 499,
    "offerPrice": 299,
    "stock": 40,
    "warranty": "6 Months Replacement",
    "rating": 4.7,
    "reviewsCount": 110,
    "featured": false,
    "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=500&q=80",
    "description": "High-density nylon braided cable supporting 65W PD fast charging & 480Mbps data sync."
  },
  {
    "id": "acc-12",
    "name": "Mi 20,000mAh 18W Fast Charging Power Bank",
    "category": "Power Banks",
    "brand": "Xiaomi",
    "sku": "MI-PB-20K",
    "price": 2499,
    "offerPrice": 1899,
    "stock": 11,
    "warranty": "6 Months Official Warranty",
    "rating": 4.8,
    "reviewsCount": 135,
    "featured": true,
    "image": "https://images.unsplash.com/photo-1609592426508-cc0496768954?auto=format&fit=crop&w=500&q=80",
    "description": "Triple port output with two-way 18W fast charging and 12 layers circuit protection."
  }
];

if (typeof window !== "undefined") {
  window.INITIAL_ACCESSORIES = INITIAL_ACCESSORIES;
}
